// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN7FH77rYPaLQ6WjJOqY47ywp0E0_CpaU',
    appId: '1:371300325277:web:ad85f69d29473c88430174',
    messagingSenderId: '371300325277',
    projectId: 'testapp-548ed',
    authDomain: 'testapp-548ed.firebaseapp.com',
    storageBucket: 'testapp-548ed.appspot.com',
    measurementId: 'G-X24YEN0CGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8jTZqHoZHwe_qY4wwIlE_J7xNJpi5Gp0',
    appId: '1:371300325277:android:4826775d438c43d2430174',
    messagingSenderId: '371300325277',
    projectId: 'testapp-548ed',
    storageBucket: 'testapp-548ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABxnJ87LWxSSZGJSrRSfeMapW62hKth9c',
    appId: '1:371300325277:ios:af2788833f2a132b430174',
    messagingSenderId: '371300325277',
    projectId: 'testapp-548ed',
    storageBucket: 'testapp-548ed.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
